### ISSUE TITLE
TP1 Aprobado: 6 (Seis)

### ISSUE THREAD

**Issue by egenender** [VickyA5/TP-Greedy-TDA#1]
Buenas! Esta primera corrección no irá al detalle de cada sección, pero porque hay elementos del TP que no están completos de acuerdo a la consigna.

> Instrucciones de uso
> Desde la carpeta base del trabajo ejecutar el comando:
> 
> python3 problema.py
> 
> Los resultados de las acciones individuales de cada jugador se guardarán en la carpeta outputs.

Las instrucciones de uso no especifican cómo cumplir la consigna, léase:

```
Debe ser claro cómo ejecutar el programa pasando por parámetro un set de datos como los que se dan de ejemplo. No debe ser necesario tener la solución esperada (sino, ¿para qué programaríamos un programa para resolver un problema cuya respuesta ya conocemos?). Esto puede ser aclarado dentro del README.md del repositorio, u otra ubicación que les parezca clara.
```

Si bien queda claro como ejercutar las pruebas según el README.md no especifica cómo probar con un nuevo archivo. Viendo el código:

```
def tests():
    output_folder = "outputs"
    if not os.path.exists(output_folder):
        os.makedirs(output_folder)

    # Tests de la cátedra
    catedra_folder = "tests_cases/catedra"
    test_files = ["20", "25", "50", "100", "1000", "10000", "20000"]
    [...]
    # Tests propios
    test_folder = "tests_cases"
    test_files_propios = [
        "test1", "test2", "test3", "test4", "test5",
        "test6", "test7", "test8", "test9", "test10"
    ]
    [...]

if __name__ == "__main__":
    tests()
```

No existe forma de probar el programa con otro archivo que se indique por parámetro del programa.

> 2.1. Algoritmo Greedy

Faltaría en esta sección describir el algoritmo planteado

> ¿Por qu´e es un algoritmo Greedy?

La justificación es genérica, solamente indica la existencia de regla Greedy. No especifica cuáles son los estados actuales, óptimos locales, óptimo global, medida de repetición en la iteración.

> Hip´otesis de inducci´on: Supongamos que el algoritmo garantiza que Sophia siempre gana para
> cualquier fila con n monedas, es decir, cuando la fila tiene n monedas, Sophia sigue la estrategia
> de elegir siempre la moneda de mayor valor y al final tendr´a m´as puntos que Mateo.
> Ahora probaremos que Sophia tambi´en ganar´a cuando la fila tenga n+1 monedas. Consideremos
> que n ¿= 3, ya que el caso de n=2 ya lo analizamos.

La hipótesis inductiva debe probarse para cualquier cantidad, no solamente n = 3

El resto de la demostración charlada no alcanza el nivel de formalidad deseado. Falta expresar en fórmulas matemáticas los montos ganados por Sophia y Mateo respectivamente, y plantear las desigualdades que permitan afirmar que gana Sophia.

Pista: aplican la metodología con n siendo la cantidad de monedas. Sugiero que lo hagan por cantidad de rondas en las que juegan tanto Sophia como Mateo.

Caso contrario, el hecho de que Sophia gane para el paso n no garantiza que gane en el n+1. En el paso n+1 si solamente juega Mateo, y solamente sabiendo que está ganando Sophia, ¿Cómo saben que Mateo no le puede superar?

> Ejemplos de ejecuci´on

Puede ser de interés desarrollar los pasos que se tomaron en 1 de los ejemplos. Para ver cómo opera el algoritmo

> Mediciones

Se percibe bastante ruido. Siendo que se hacen ejemplos desde 100 monedas hasta 100 millones, 30 muestras parece ser un número pequeño en comparación.

>  cada partida es ejecutada 10 veces para obtener una
> estimaci´on m´as precisa de los tiempos de ejecuci´on del programa

Pueden también analizar aumentar esa valor para ver si se obtienen gráficos con menos ruido.

> Hicimos un ajuste lineal, uno n ∗ log(n) y uno n2

Comparando O(n) y O(n log n), el ruido es muy propenso a no permitir distinguir

Falta de la consigna:

- Analizar si (y cómo) afecta la variabilidad de los valores de las diferentes monedas a los tiempos del algoritmo planteado.

- Analizar si (y cómo) afecta la variabilidad de los valores de las diferentes monedas a la optimalidad del algoritmo planteado.

> - Realizar ejemplos de ejecución para encontrar soluciones y corroborar lo encontrado. Adicionalmente, el curso proveerá con algunos casos particulares que deben cumplirse su optimalidad también.

En este caso los ejemplos agregados son pocos. Recomiendo la generación automática de nuevos ejemplos. Analizar (si) gane Sophia en todos los casos

**Comment by fmonpelat** [comment]
@egenender por curiosidad me pregunto, ni en clase vimos rigurosidad matematica para problemas greedy, porque se nos pide en el TP? porque veo que nos estas pidiendo:
`El resto de la demostración charlada no alcanza el nivel de formalidad deseado. Falta expresar en fórmulas matemáticas los montos ganados por Sophia y Mateo respectivamente, y plantear las desigualdades que permitan afirmar que gana Sophia.
`
diria que no entendemos exactamente que hacer en este punto.

**Comment by egenender** [comment]
> @egenender por curiosidad me pregunto, ni en clase vimos rigurosidad matematica para problemas greedy, porque se nos pide en el TP? porque veo que nos estas pidiendo: `El resto de la demostración charlada no alcanza el nivel de formalidad deseado. Falta expresar en fórmulas matemáticas los montos ganados por Sophia y Mateo respectivamente, y plantear las desigualdades que permitan afirmar que gana Sophia. ` diria que no entendemos exactamente que hacer en este punto.

Por poner un ejemplo, las primeras dos monedas tomadas en el juego pueden llamarse s1 la tomada por Sophia y m1 la tomada por Mateo. El nivel mínimo de rigurosidad debería ser al menos plantear la desigualdad `s1 > m1` y de alguna manera desmostrar cómo, siguiendo el algoritmo greedy, Sophia siempre ganará el juego

**Comment by egenender** [comment]
TP1 Aprobado: 6 (Seis)
